version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: celery.Dockerfile
    command: >
      poetry run celery -A celery_app.config.app_celery worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  ollama_data: